import { readFile } from 'fs/promises'
import path from 'path'
import { jsonSchemaOutputFormat } from '@anthropic-ai/sdk/helpers/json-schema'
import { anthropic } from './anthropic'
import { previousEdition, type ReportPeriod } from './edition'

// ─── The weekly leadership update ────────────────────────────────────────────
//
// Turns one EDITION of CHANGELOG.md — a Monday-to-Sunday work week, named after
// its Monday (see lib/edition.ts) — into a one-page summary a director can read
// in about two minutes, and mails it as a Word attachment with the engineering
// detail appended.
//
// The job runs on a Monday and reports the edition that CLOSED the day before,
// so every change is reported exactly once. A rolling "last seven days from now"
// window used to decide membership by the hour the job happened to fire, which
// meant an entry could land in two consecutive reports or in neither.
//
// Length is a deliberate setting, not an accident: the brief targets 16-22 lines
// of at most two short sentences each. An earlier pass at ~11 terse lines read in
// 25 seconds but lost the "so what" — Jacob asked for more room to explain, on
// the assumption the reader is not technical and wants the picture, not the gist.
//
// ── Why the changelog is the source ─────────────────────────────────────────
// Because it is already written, already accurate, and already updated on every
// deploy (a standing rule). Deriving the update from git subjects instead would
// mean summarizing commit messages, which describe code; the changelog entries
// describe what changed for the business, which is what leadership is asking
// about. It also means this report cannot drift from reality — if nothing was
// written to the changelog, nothing is claimed.
//
// ── Why an LLM ──────────────────────────────────────────────────────────────
// The changelog is written for the next engineer: it names files, env vars and
// migrations. Leadership needs the same facts in their own terms. That is a
// translation, not an invention — the prompt below forbids adding anything not
// present in the source, because a report that quietly embellishes is worse
// than no report.

export type UpdateSection = { title: string; items: string[] }

export type LeadershipUpdate = {
  /** Which period this report covers — an edition, or an interim range. See lib/edition.ts. */
  period: { id: string; label: string; range: string; kind: 'edition' | 'interim' }
  /** Part 1 — the non-technical read. Two minutes, a director's vocabulary. */
  sections: UpdateSection[]
  /**
   * Part 2 — the engineering read, for whoever has to act on it. Generated by a
   * SECOND model call rather than a second half of the first one: the two serve
   * opposite registers, and one prompt asked to do both drifts into a middle
   * voice that serves neither. Empty if that call fails — a missing technical
   * half must never cost leadership their summary.
   */
  technical: UpdateSection[]
  /** Entry headings that fed the summary — logged so a thin week is explicable. */
  sourceEntries: string[]
}

const CHANGELOG = path.join(process.cwd(), 'CHANGELOG.md')

/**
 * Changelog entries belonging to one edition — dated on or after its Monday and
 * before the next. Entries are `## YYYY-MM-DD — title` and newest-first, so we
 * skip past anything newer and stop once one falls below the start.
 *
 * Replaced a rolling "last 7 days from now" window. That window depended on the
 * hour the job happened to run, so an entry could appear in two consecutive
 * reports or in neither, and a report could never honestly claim to BE an
 * edition. A closed Monday-to-Sunday range covers each change exactly once.
 */
export function entriesForPeriod(markdown: string, period: ReportPeriod): { heading: string; body: string }[] {
  const parts = markdown.split(/^## /m).slice(1)
  const out: { heading: string; body: string }[] = []

  for (const part of parts) {
    const newline = part.indexOf('\n')
    const heading = (newline === -1 ? part : part.slice(0, newline)).trim()
    const dateMatch = /^(\d{4}-\d{2}-\d{2})/.exec(heading)
    if (!dateMatch) continue
    // Midday avoids a timezone shift pushing an entry over the boundary.
    const entryDate = new Date(`${dateMatch[1]}T12:00:00Z`)
    if (entryDate < period.start) break
    // Newer than this edition — a later week's work, seen first because the file
    // is newest-first. Skip rather than break, or nothing older would be reached.
    if (entryDate >= period.end) continue
    out.push({ heading, body: newline === -1 ? '' : part.slice(newline + 1).trim() })
  }
  return out
}

// ── The prompts are period-aware in exactly three places ────────────────────
// What the input is, what the report is called, and how long it should run to.
// An interim covers a couple of days, so a brief still saying "the past week"
// would have the model writing a weekly summary over partial input — and, worse,
// producing lines that say "this week" to a reader holding two days of it.
//
// For an EDITION every string below is identical to what it has always been, so
// the Monday report is unchanged by the interim path existing at all.

const isWeek = (p: ReportPeriod) => p.kind === 'edition'

const SYSTEM = (p: ReportPeriod) => `You write the ${isWeek(p) ? 'weekly' : 'interim'} one-page update for the leadership team of Innovative Air Technologies, an industrial dehumidification manufacturer. Your input is the engineering changelog for ${isWeek(p) ? 'the past week' : `${p.range} — a few days, not a full week`}.

Your reader is a director or owner. They are NOT technical. They will give this about two minutes.

THE HARD RULE
Each line is AT MOST TWO short sentences and AT MOST 28 WORDS in total. Count them. The first sentence says what changed; an optional second says why it matters or what it cost. Never a third.

WHAT TO WRITE
- The business outcome only. What can someone now do, or what stopped being broken.
- Never how it was built. No file names, no error codes, no percentages of anything technical, no product model numbers, no words like: endpoint, cron, idempotency, server, API, environment variable, reCAPTCHA, migration, bisection, canonical, permissions, round-trip.
- Problems found and fixed belong here, stated plainly and without blame or drama.
- When something was broken, say what it COST — how long it ran, or what was missed. "Six customer tickets went unseen for ten days" earns its words; "alerts now deliver reliably" hides the story leadership needs.
- Invent NOTHING. Every line must trace to the input. A quiet ${isWeek(p) ? 'week' : 'stretch'} gets fewer lines, not padding.
- NEVER state a number, duration or date that is not explicitly in the input. If the input says "had never run since it was built", write that — do not compute or guess how long that was. A figure a director might repeat in a meeting must be one we actually wrote down.
- Never name a customer, a customer's company, or a competitor. Say "a customer".
- Plain business English. No marketing language, no exclamation marks, no emoji.${isWeek(p) ? '' : `
- This update covers ${p.range} ONLY, which is part of a week and not a whole one. Never write "this week", "the week", or "last week" — say "these past few days", or simply state what changed without dating it.`}

EXAMPLES

Input mentions a missing CRON_SECRET meaning cron routes 401'd and digest_runs was empty.
BAD:  "Scheduled jobs have never run since launch. The authentication secret was missing, so every cron route returned 401. Fixed and verified."
GOOD: "Scheduled background jobs had never run since launch. The daily management summary and weekly leave accrual now work for the first time."

Input describes a guided RFQ wizard with 18 presets producing a 5-page PDF.
BAD:  "Quote requests can be submitted through a guided moisture survey form. Replaces emailed Word attachments. Eighteen room applications and eleven process types seed typical values."
GOOD: "Customers can now complete a full moisture survey online in about three minutes. It replaces the Word form we used to email out."

Input describes append-only notes with author snapshots and assignee permission checks.
BAD:  "Quote requests gain an owner and permanent note trail. Each request assigns to someone holding deals permissions. Notes are append-only with timestamps and attribution."
GOOD: "Every quote request now has a named owner and a permanent note history. Notes are stamped with who wrote them and cannot be edited later."

SHAPE
At most 4 sections, titles in capitals (NEW, FIXED, IMPROVED are usually right).
BETWEEN ${isWeek(p) ? '16 AND 22' : '12 AND 18'} lines in total across all sections — enough that a reader finishes with the full picture of ${isWeek(p) ? 'the week' : 'these few days'}, not so many that it stops being a summary. Merge closely related items rather than listing every one.

Group the lines into sections, each with a capitalised title.`

const TECHNICAL_SYSTEM = (p: ReportPeriod) => `You write the engineering half of ${isWeek(p) ? 'a weekly report' : 'an interim report'} for the person who maintains the IAT Portal. Your input is the engineering changelog for ${isWeek(p) ? 'the past week' : `${p.range} — a few days, not a full week`}.

Your reader BUILT this system. They want the detail the leadership summary deliberately drops, as notes they can act on months later.

WHAT TO WRITE
- The mechanism, not the outcome. What actually changed, and the reasoning that is not obvious from the result.
- Specifics are the point: file and table names, migration numbers, thresholds, env var names, status codes, the shape of a guard. These are REQUIRED here, unlike in the leadership half.
- When something was broken, say what the root cause was and why it was invisible — that is the part worth remembering.
- Call out anything shipped but NOT verified, and anything left deliberately undone. A gap silently omitted is the most expensive line in the report.
- Invent NOTHING. Every line must trace to the input. Do not state a number, duration or count that is not written in the source.

WHAT NOT TO WRITE
- No praise, no summary-of-the-summary, no "this improves reliability" filler.
- Never a customer name, a customer's company, or a competitor name. Suppliers are fine.
- NO MARKDOWN. These lines are rendered into a Word document that does not interpret it, so asterisks and backticks print literally — **bold**, *italics* and \`code\` all arrive as punctuation on the page. Write file names, env vars and values as plain words.

LENGTH
Sections titled in capitals. Group by theme — SECURITY, FIXES, FEATURES, INFRASTRUCTURE, GAPS are usually right, but follow ${isWeek(p) ? 'the week' : 'the material'}.
Up to 6 sections and up to ${isWeek(p) ? '30' : '24'} lines total. Each line at most 45 words. One sentence is usually enough; two is the ceiling.
The last section should be GAPS or OPEN — what is unverified, unfinished, or waiting on a decision.

Group the lines into sections, each with a capitalised title.`

/**
 * The model's JSON, or null if it did not produce any.
 *
 * ⚠️ THE FAILURE THIS EXISTS FOR: a line containing a quoted phrase — a customer
 * who pressed the button got 'no ticket found' — arrives as unescaped double
 * quotes inside a JSON string, and JSON.parse throws. It is not exotic: the brief
 * is written in quoted examples, so the model reaches for that punctuation.
 *
 * Unhandled it cost the whole report. The leadership half threw straight out of
 * buildLeadershipUpdate and the route answered 500, so NOTHING sent. The technical
 * half sat inside a try/catch and came back silently empty — which is how the
 * 2026-08-19 send went out with page 1, no page 2, and no alarm anywhere.
 *
 * Returning null instead lets both halves retry with the fault named.
 */
const SECTIONS_SCHEMA = {
  type: 'object',
  properties: {
    sections: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          title: { type: 'string' },
          items: { type: 'array', items: { type: 'string' } },
        },
        required: ['title', 'items'],
        additionalProperties: false,
      },
    },
  },
  required: ['sections'],
  additionalProperties: false,
} as const

/** What one call to the model produced, and why it produced nothing if it did not. */
type SectionsReply = {
  sections: UpdateSection[] | null
  /** Distinguishes the three reasons for null. Never guess between them. */
  reason: 'ok' | 'refusal' | 'truncated' | 'unparseable'
  stopReason: string | null
}

/**
 * Ask for sections with the SHAPE ENFORCED BY THE API, not by the prompt.
 *
 * ⚠️ WHY THIS IS NOT `JSON.parse` ANY MORE. Both halves used to ask for JSON in
 * the prompt and parse the reply by hand, and it failed in production twice:
 * 2026-08-19 (page 2 missing, nobody noticed) and 2026-08-26.
 *
 * 🔴 The 2026-08-26 diagnosis in the log was WRONG, and the wrongness is the
 * lesson. A null parse with `stop_reason !== 'max_tokens'` was reported as
 * "bad escaping" — a guess, printed as a fact. The model had actually returned
 * `stop_reason: 'refusal'` and no JSON at all. The retry then told it to fix
 * unescaped double quotes, a fault that was not there, so the second attempt
 * failed the same way. Reproduced against that night's changelog: the shipped
 * path refused twice, structured output parsed the same input cleanly twice.
 *
 * So: the schema is now the contract, and `reason` is measured rather than
 * assumed — a refusal is never retried as if it were a formatting slip.
 */
async function askForSections(
  system: string,
  messages: { role: 'user' | 'assistant'; content: string }[],
  maxTokens: number,
): Promise<SectionsReply> {
  const res = await anthropic.messages.parse({
    model: 'claude-sonnet-4-5',
    max_tokens: maxTokens,
    system,
    messages,
    output_config: { format: jsonSchemaOutputFormat(SECTIONS_SCHEMA) },
  })
  const stopReason = res.stop_reason ?? null
  const parsed = res.parsed_output as { sections?: UpdateSection[] } | null

  const sections = (parsed?.sections ?? []).filter(
    s => s && typeof s.title === 'string' && Array.isArray(s.items) && s.items.length,
  )
  if (sections.length) return { sections, reason: 'ok', stopReason }

  return {
    sections: null,
    reason: stopReason === 'refusal' ? 'refusal'
      : stopReason === 'max_tokens' ? 'truncated'
        : 'unparseable',
    stopReason,
  }
}

/**
 * Token ceilings. Raised from 2000/3000 on 2026-08-20: a three-day stretch with 27
 * changelog entries (38k characters of source) ran the summary past 2000 tokens and
 * the reply stopped MID-JSON, so every parse failed identically on every retry.
 * Truncation is deterministic — retrying the same call cannot fix it, which is why
 * it has to be detected rather than retried blindly.
 */
const MAX_TOKENS_SUMMARY = 4000
const MAX_TOKENS_TECHNICAL = 4000

/** Why a response would not parse. The two causes need opposite corrections. */
function repairPrompt(truncated: boolean): string {
  return truncated
    ? 'Your reply was cut off before the JSON closed — it was too long. Send the '
      + 'whole thing again, materially SHORTER: merge related items aggressively and '
      + 'stay at the low end of the line count you were given.'
    // No longer about escaping: the schema makes malformed JSON impossible, so
    // the only remaining non-truncation failure is an empty or section-less
    // answer. Naming quotes here was actively harmful — it sent the model to fix
    // a fault it did not have while the real one (a refusal) went unaddressed.
    : 'That came back with no usable sections. Send the whole response again, '
      + 'same facts, grouped into at least one titled section with at least one '
      + 'line in it.'
}


/**
 * Lines that break the brief, so a bad generation can be caught and retried.
 * Thresholds sit slightly above the prompt's stated limits (28 words, 2 sentences)
 * so a line that is a shade long is allowed through — the gate is for lines that
 * have clearly reverted to explaining the engineering, not for hairline overruns.
 */
function offenders(sections: UpdateSection[]): string[] {
  const BANNED = /\b(endpoint|cron|idempotenc|API|environment variable|reCAPTCHA|migration|bisection|canonical|round-trip|401|server[- ]side|permissions)\b/i
  return sections.flatMap(s => s.items).filter(
    line => line.split(/\s+/).length > 32 || (line.match(/\./g) ?? []).length > 2 || BANNED.test(line),
  )
}

/**
 * Build the update for one period. Defaults to the LAST COMPLETE EDITION — the
 * job runs on a Monday, and that Monday's own work belongs to the edition just
 * beginning, not the one being reported. Pass an edition explicitly to rebuild an
 * older week, or an interimPeriod() to cover a few days without disturbing the
 * edition that contains them.
 */
export async function buildLeadershipUpdate(
  period: ReportPeriod = previousEdition(new Date()),
): Promise<LeadershipUpdate> {
  const markdown = await readFile(CHANGELOG, 'utf8')
  const entries = entriesForPeriod(markdown, period)

  const ed = { id: period.id, label: period.label, range: period.range, kind: period.kind }
  if (!entries.length) {
    return { period: ed, sections: [], technical: [], sourceEntries: [] }
  }

  const source = entries.map(e => `## ${e.heading}\n${e.body}`).join('\n\n')

  // One retry with the offending lines quoted back. The first pass reliably
  // over-writes — it wants to explain the engineering — and naming the specific
  // lines that broke the brief fixes it far more often than restating the rules.
  let sections: UpdateSection[] = []
  const messages: { role: 'user' | 'assistant'; content: string }[] = [
    { role: 'user', content: source.slice(0, 60000) },
  ]

  const LAST = 2
  for (let attempt = 0; attempt <= LAST; attempt++) {
    const reply = await askForSections(SYSTEM(period), messages, MAX_TOKENS_SUMMARY)

    if (!reply.sections) {
      console.warn(`[leadership] attempt ${attempt + 1}: no sections (${reply.reason}, stop_reason ${reply.stopReason})`)
      // A refusal is not a formatting problem, and asking the model to try again
      // the same way just spends another call to be refused again — measured on
      // 2026-08-26, twice in a row on the same input.
      if (attempt === LAST || reply.reason === 'refusal') {
        throw new Error(`leadership update: no sections (${reply.reason}, last stop_reason: ${reply.stopReason})`)
      }
      messages.push({ role: 'user', content: repairPrompt(reply.reason === 'truncated') })
      continue
    }
    sections = reply.sections

    const bad = offenders(sections)
    if (!bad.length) break
    if (attempt === LAST) {
      // Still over-long. Ship it rather than send nothing — a wordy update beats
      // a silent Monday — but say so in the log.
      console.warn(`[leadership] ${bad.length} line(s) still over the brief after a retry`)
      break
    }
    // The model's own turn is echoed back as the JSON we actually parsed, rather
    // than the raw reply text it used to be — structured output means there is no
    // loose text to quote, and the parsed form is what the critique refers to.
    messages.push(
      { role: 'assistant', content: JSON.stringify({ sections }) },
      {
        role: 'user',
        content: `These lines break the brief — each is over 28 words, runs to three or more sentences, or uses banned technical vocabulary:\n\n${bad.map(b => `- ${b}`).join('\n')}\n\nRewrite the WHOLE response. Same facts, same shape, but every line at most two short sentences a director would read aloud in a meeting. Between ${isWeek(period) ? '16 and 22' : '12 and 18'} lines total.`,
      },
    )
  }

  // ── Part 2: the engineering read ──
  // A separate call, and deliberately NOT gated by offenders(): that validator
  // exists to stop the leadership half reverting to engineering vocabulary, which
  // is precisely what this half is supposed to use. Wrapped so a failure here
  // costs the technical notes only — leadership still gets their summary, which
  // is the half with a deadline.
  let technical: UpdateSection[] = []
  try {
    const msgs: { role: 'user' | 'assistant'; content: string }[] = [
      { role: 'user', content: source.slice(0, 60000) },
    ]
    for (let attempt = 0; attempt < 2; attempt++) {
      const reply = await askForSections(TECHNICAL_SYSTEM(period), msgs, MAX_TOKENS_TECHNICAL)
      if (reply.sections) { technical = reply.sections; break }
      console.warn(`[leadership] technical half attempt ${attempt + 1}: ${reply.reason} (stop_reason ${reply.stopReason})`)
      // Same reasoning as the leadership half — a refusal will not be talked out
      // of itself, and this is the half that fails silently, so do not burn the
      // second call pretending it is a formatting problem.
      if (reply.reason === 'refusal') break
      msgs.push({ role: 'user', content: repairPrompt(reply.reason === 'truncated') })
    }
    // ERROR, not warn. This half vanishing is invisible from outside — the only
    // tell in the delivered email is one clause of one sentence — and it shipped
    // exactly that way on 2026-08-19 with nobody noticing.
    if (!technical.length) {
      console.error('[leadership] TECHNICAL HALF EMPTY — report ships with part 1 only')
    }
  } catch (err) {
    console.error('[leadership] technical half failed — sending the leadership summary alone:', err)
  }

  return { period: ed, sections, technical, sourceEntries: entries.map(e => e.heading) }
}
