import { readFile } from 'fs/promises'
import path from 'path'
import { anthropic } from './anthropic'
import { previousEdition, type ReportPeriod } from './edition'

// ─── The weekly leadership update ────────────────────────────────────────────
//
// Turns one EDITION of CHANGELOG.md — a Monday-to-Sunday work week, named after
// its Monday (see lib/edition.ts) — into a one-page summary a director can read
// in about two minutes, and mails it as a Word attachment with the engineering
// detail appended.
//
// The job runs on a Monday and reports the edition that CLOSED the day before,
// so every change is reported exactly once. A rolling "last seven days from now"
// window used to decide membership by the hour the job happened to fire, which
// meant an entry could land in two consecutive reports or in neither.
//
// Length is a deliberate setting, not an accident: the brief targets 16-22 lines
// of at most two short sentences each. An earlier pass at ~11 terse lines read in
// 25 seconds but lost the "so what" — Jacob asked for more room to explain, on
// the assumption the reader is not technical and wants the picture, not the gist.
//
// ── Why the changelog is the source ─────────────────────────────────────────
// Because it is already written, already accurate, and already updated on every
// deploy (a standing rule). Deriving the update from git subjects instead would
// mean summarising commit messages, which describe code; the changelog entries
// describe what changed for the business, which is what leadership is asking
// about. It also means this report cannot drift from reality — if nothing was
// written to the changelog, nothing is claimed.
//
// ── Why an LLM ──────────────────────────────────────────────────────────────
// The changelog is written for the next engineer: it names files, env vars and
// migrations. Leadership needs the same facts in their own terms. That is a
// translation, not an invention — the prompt below forbids adding anything not
// present in the source, because a report that quietly embellishes is worse
// than no report.

export type UpdateSection = { title: string; items: string[] }

export type LeadershipUpdate = {
  /** Which period this report covers — an edition, or an interim range. See lib/edition.ts. */
  period: { id: string; label: string; range: string; kind: 'edition' | 'interim' }
  /** Part 1 — the non-technical read. Two minutes, a director's vocabulary. */
  sections: UpdateSection[]
  /**
   * Part 2 — the engineering read, for whoever has to act on it. Generated by a
   * SECOND model call rather than a second half of the first one: the two serve
   * opposite registers, and one prompt asked to do both drifts into a middle
   * voice that serves neither. Empty if that call fails — a missing technical
   * half must never cost leadership their summary.
   */
  technical: UpdateSection[]
  /** Entry headings that fed the summary — logged so a thin week is explicable. */
  sourceEntries: string[]
}

const CHANGELOG = path.join(process.cwd(), 'CHANGELOG.md')

/**
 * Changelog entries belonging to one edition — dated on or after its Monday and
 * before the next. Entries are `## YYYY-MM-DD — title` and newest-first, so we
 * skip past anything newer and stop once one falls below the start.
 *
 * Replaced a rolling "last 7 days from now" window. That window depended on the
 * hour the job happened to run, so an entry could appear in two consecutive
 * reports or in neither, and a report could never honestly claim to BE an
 * edition. A closed Monday-to-Sunday range covers each change exactly once.
 */
export function entriesForPeriod(markdown: string, period: ReportPeriod): { heading: string; body: string }[] {
  const parts = markdown.split(/^## /m).slice(1)
  const out: { heading: string; body: string }[] = []

  for (const part of parts) {
    const newline = part.indexOf('\n')
    const heading = (newline === -1 ? part : part.slice(0, newline)).trim()
    const dateMatch = /^(\d{4}-\d{2}-\d{2})/.exec(heading)
    if (!dateMatch) continue
    // Midday avoids a timezone shift pushing an entry over the boundary.
    const entryDate = new Date(`${dateMatch[1]}T12:00:00Z`)
    if (entryDate < period.start) break
    // Newer than this edition — a later week's work, seen first because the file
    // is newest-first. Skip rather than break, or nothing older would be reached.
    if (entryDate >= period.end) continue
    out.push({ heading, body: newline === -1 ? '' : part.slice(newline + 1).trim() })
  }
  return out
}

// ── The prompts are period-aware in exactly three places ────────────────────
// What the input is, what the report is called, and how long it should run to.
// An interim covers a couple of days, so a brief still saying "the past week"
// would have the model writing a weekly summary over partial input — and, worse,
// producing lines that say "this week" to a reader holding two days of it.
//
// For an EDITION every string below is identical to what it has always been, so
// the Monday report is unchanged by the interim path existing at all.

const isWeek = (p: ReportPeriod) => p.kind === 'edition'

const SYSTEM = (p: ReportPeriod) => `You write the ${isWeek(p) ? 'weekly' : 'interim'} one-page update for the leadership team of Innovative Air Technologies, an industrial dehumidification manufacturer. Your input is the engineering changelog for ${isWeek(p) ? 'the past week' : `${p.range} — a few days, not a full week`}.

Your reader is a director or owner. They are NOT technical. They will give this about two minutes.

THE HARD RULE
Each line is AT MOST TWO short sentences and AT MOST 28 WORDS in total. Count them. The first sentence says what changed; an optional second says why it matters or what it cost. Never a third.

WHAT TO WRITE
- The business outcome only. What can someone now do, or what stopped being broken.
- Never how it was built. No file names, no error codes, no percentages of anything technical, no product model numbers, no words like: endpoint, cron, idempotency, server, API, environment variable, reCAPTCHA, migration, bisection, canonical, permissions, round-trip.
- Problems found and fixed belong here, stated plainly and without blame or drama.
- When something was broken, say what it COST — how long it ran, or what was missed. "Six customer tickets went unseen for ten days" earns its words; "alerts now deliver reliably" hides the story leadership needs.
- Invent NOTHING. Every line must trace to the input. A quiet ${isWeek(p) ? 'week' : 'stretch'} gets fewer lines, not padding.
- NEVER state a number, duration or date that is not explicitly in the input. If the input says "had never run since it was built", write that — do not compute or guess how long that was. A figure a director might repeat in a meeting must be one we actually wrote down.
- Never name a customer, a customer's company, or a competitor. Say "a customer".
- Plain business English. No marketing language, no exclamation marks, no emoji.${isWeek(p) ? '' : `
- This update covers ${p.range} ONLY, which is part of a week and not a whole one. Never write "this week", "the week", or "last week" — say "these past few days", or simply state what changed without dating it.`}

EXAMPLES

Input mentions a missing CRON_SECRET meaning cron routes 401'd and digest_runs was empty.
BAD:  "Scheduled jobs have never run since launch. The authentication secret was missing, so every cron route returned 401. Fixed and verified."
GOOD: "Scheduled background jobs had never run since launch. The daily management summary and weekly leave accrual now work for the first time."

Input describes a guided RFQ wizard with 18 presets producing a 5-page PDF.
BAD:  "Quote requests can be submitted through a guided moisture survey form. Replaces emailed Word attachments. Eighteen room applications and eleven process types seed typical values."
GOOD: "Customers can now complete a full moisture survey online in about three minutes. It replaces the Word form we used to email out."

Input describes append-only notes with author snapshots and assignee permission checks.
BAD:  "Quote requests gain an owner and permanent note trail. Each request assigns to someone holding deals permissions. Notes are append-only with timestamps and attribution."
GOOD: "Every quote request now has a named owner and a permanent note history. Notes are stamped with who wrote them and cannot be edited later."

SHAPE
At most 4 sections, titles in capitals (NEW, FIXED, IMPROVED are usually right).
BETWEEN ${isWeek(p) ? '16 AND 22' : '12 AND 18'} lines in total across all sections — enough that a reader finishes with the full picture of ${isWeek(p) ? 'the week' : 'these few days'}, not so many that it stops being a summary. Merge closely related items rather than listing every one.

Return ONLY valid JSON, no prose around it:
{"sections":[{"title":"NEW","items":["...","..."]}]}`

const TECHNICAL_SYSTEM = (p: ReportPeriod) => `You write the engineering half of ${isWeek(p) ? 'a weekly report' : 'an interim report'} for the person who maintains the IAT Portal. Your input is the engineering changelog for ${isWeek(p) ? 'the past week' : `${p.range} — a few days, not a full week`}.

Your reader BUILT this system. They want the detail the leadership summary deliberately drops, as notes they can act on months later.

WHAT TO WRITE
- The mechanism, not the outcome. What actually changed, and the reasoning that is not obvious from the result.
- Specifics are the point: file and table names, migration numbers, thresholds, env var names, status codes, the shape of a guard. These are REQUIRED here, unlike in the leadership half.
- When something was broken, say what the root cause was and why it was invisible — that is the part worth remembering.
- Call out anything shipped but NOT verified, and anything left deliberately undone. A gap silently omitted is the most expensive line in the report.
- Invent NOTHING. Every line must trace to the input. Do not state a number, duration or count that is not written in the source.

WHAT NOT TO WRITE
- No praise, no summary-of-the-summary, no "this improves reliability" filler.
- Never a customer name, a customer's company, or a competitor name. Suppliers are fine.

LENGTH
Sections titled in capitals. Group by theme — SECURITY, FIXES, FEATURES, INFRASTRUCTURE, GAPS are usually right, but follow ${isWeek(p) ? 'the week' : 'the material'}.
Up to 6 sections and up to ${isWeek(p) ? '30' : '24'} lines total. Each line at most 45 words. One sentence is usually enough; two is the ceiling.
The last section should be GAPS or OPEN — what is unverified, unfinished, or waiting on a decision.

Return ONLY this JSON:
{"sections":[{"title":"SECURITY","items":["...","..."]}]}`

/**
 * Lines that break the brief, so a bad generation can be caught and retried.
 * Thresholds sit slightly above the prompt's stated limits (28 words, 2 sentences)
 * so a line that is a shade long is allowed through — the gate is for lines that
 * have clearly reverted to explaining the engineering, not for hairline overruns.
 */
function offenders(sections: UpdateSection[]): string[] {
  const BANNED = /\b(endpoint|cron|idempotenc|API|environment variable|reCAPTCHA|migration|bisection|canonical|round-trip|401|server[- ]side|permissions)\b/i
  return sections.flatMap(s => s.items).filter(
    line => line.split(/\s+/).length > 32 || (line.match(/\./g) ?? []).length > 2 || BANNED.test(line),
  )
}

/**
 * Build the update for one period. Defaults to the LAST COMPLETE EDITION — the
 * job runs on a Monday, and that Monday's own work belongs to the edition just
 * beginning, not the one being reported. Pass an edition explicitly to rebuild an
 * older week, or an interimPeriod() to cover a few days without disturbing the
 * edition that contains them.
 */
export async function buildLeadershipUpdate(
  period: ReportPeriod = previousEdition(new Date()),
): Promise<LeadershipUpdate> {
  const markdown = await readFile(CHANGELOG, 'utf8')
  const entries = entriesForPeriod(markdown, period)

  const ed = { id: period.id, label: period.label, range: period.range, kind: period.kind }
  if (!entries.length) {
    return { period: ed, sections: [], technical: [], sourceEntries: [] }
  }

  const source = entries.map(e => `## ${e.heading}\n${e.body}`).join('\n\n')

  // One retry with the offending lines quoted back. The first pass reliably
  // over-writes — it wants to explain the engineering — and naming the specific
  // lines that broke the brief fixes it far more often than restating the rules.
  let sections: UpdateSection[] = []
  const messages: { role: 'user' | 'assistant'; content: string }[] = [
    { role: 'user', content: source.slice(0, 60000) },
  ]

  for (let attempt = 0; attempt < 2; attempt++) {
    const res = await anthropic.messages.create({
      model: 'claude-sonnet-4-5',
      max_tokens: 2000,
      system: SYSTEM(period),
      messages,
    })
    const text = res.content.map(b => (b.type === 'text' ? b.text : '')).join('')

    // Told to return bare JSON, but a stray code fence is the one failure worth
    // tolerating rather than throwing the week's report away.
    const json = /\{[\s\S]*\}/.exec(text)
    if (!json) throw new Error('leadership update: model returned no JSON')

    const parsed = JSON.parse(json[0]) as { sections?: UpdateSection[] }
    sections = (parsed.sections ?? []).filter(
      s => s && typeof s.title === 'string' && Array.isArray(s.items) && s.items.length,
    )
    if (!sections.length) throw new Error('leadership update: model returned no sections')

    const bad = offenders(sections)
    if (!bad.length) break
    if (attempt === 1) {
      // Second pass still over-long. Ship it rather than send nothing — a wordy
      // update beats a silent Monday — but say so in the log.
      console.warn(`[leadership] ${bad.length} line(s) still over the brief after a retry`)
      break
    }
    messages.push(
      { role: 'assistant', content: text },
      {
        role: 'user',
        content: `These lines break the brief — each is over 28 words, runs to three or more sentences, or uses banned technical vocabulary:\n\n${bad.map(b => `- ${b}`).join('\n')}\n\nRewrite the WHOLE response. Same facts, same JSON shape, but every line at most two short sentences a director would read aloud in a meeting. Between ${isWeek(period) ? '16 and 22' : '12 and 18'} lines total.`,
      },
    )
  }

  // ── Part 2: the engineering read ──
  // A separate call, and deliberately NOT retried or gated by offenders(): that
  // validator exists to stop the leadership half reverting to engineering
  // vocabulary, which is precisely what this half is supposed to use. Wrapped so
  // a failure here costs the technical notes only — leadership still gets their
  // summary, which is the half with a deadline.
  let technical: UpdateSection[] = []
  try {
    const res = await anthropic.messages.create({
      model: 'claude-sonnet-4-5',
      max_tokens: 3000,
      system: TECHNICAL_SYSTEM(period),
      messages: [{ role: 'user', content: source.slice(0, 60000) }],
    })
    const text = res.content.map(b => (b.type === 'text' ? b.text : '')).join('')
    const json = /\{[\s\S]*\}/.exec(text)
    if (json) {
      const parsed = JSON.parse(json[0]) as { sections?: UpdateSection[] }
      technical = (parsed.sections ?? []).filter(
        s => s && typeof s.title === 'string' && Array.isArray(s.items) && s.items.length,
      )
    }
    if (!technical.length) console.warn('[leadership] technical half came back empty')
  } catch (err) {
    console.error('[leadership] technical half failed — sending the leadership summary alone:', err)
  }

  return { period: ed, sections, technical, sourceEntries: entries.map(e => e.heading) }
}
