// ─── RFQ application → room render ───────────────────────────────────────────
//
// Which picture to show beside the survey once the customer picks their
// application on step 2. The render then rides along in the right rail for the
// rest of the wizard, so they can see the room they are describing.
//
// This map is HAND-MAINTAINED and lives here rather than in lib/render-assets.ts,
// which is generated by the convert/upload scripts and must not be hand-edited.
//
// ⚠️ Pair by explicit key, never by string munging. The two vocabularies drifted
// independently: the RFQ says `pharma`, the artwork says `pharmaceutical`; the RFQ
// says `dry-room` for a lithium battery room, the artwork says `battery`. A
// startsWith/includes match would mis-pair several and silently show a customer
// the wrong room.
//
// Every value below is a key in the `rooms` set — 1920x1080, 16:9, WITH a
// background. Deliberately not `rooms-cutout`: those are transparent, trimmed to
// content, ~1.31:1, and are the set the overlay compositing warnings apply to.
// Nothing here composites, so none of that matters — but the two sets are not
// interchangeable in one layout slot, so the set is pinned.
//
// Chosen by looking at the artwork, not by reading filenames. Several are a
// judgment call rather than a match, and are marked so they can be re-decided:
//   candy            → processing-1     a food line with a coating conveyor
//   archive          → museum-no-glass  the label leads with "Museum"
//   electronics      → electrical-lab-pcb  board assembly, not a general cleanroom
//   restoration      → residential-1    structural drying is usually a building interior
//   investment-casting → manufacturing  nearest heavy-industrial shop
//   powder           → conveying        material transport rather than the pack-out
//   coatings         → automotive       the robot paint line
//   lyo              → pharmaceutical   lyophilizers live in pharma
//
// `cannabis` maps to `cannabis-room` (drying trays) and NOT `grow-room`
// (a greenhouse). The RFQ preset is "Cannabis dry / cure", which is the former.
//
// ⚠️ `natatorium` (indoor pool) is deliberately ABSENT: there is no pool render in
// the set. An unmapped preset shows no picture, which is correct — a wrong room is
// worse than no room. Add the key here if a pool render is ever produced.

/** RFQ preset key (room or process track) → key in the `rooms` render set. */
export const PRESET_RENDER: Record<string, string> = {
  // ── Room track ──
  'warehouse':          'long-term-storage',
  'cold-storage':       'cooler-freezer',
  'freezer':            'cooler-freezer',
  'pharma':             'pharmaceutical',
  'dry-room':           'battery',
  'food':               'food',
  'candy':              'processing-1',
  'ice-rink':           'ice-rink',
  'water-treatment':    'water-treatment-plant',
  'archive':            'museum-no-glass-case',
  'military':           'military',
  'cannabis':           'cannabis-room',
  'seed':               'silo',
  // 'natatorium'    — no pool render exists; see the note above.
  'electronics':        'electrical-lab-pcb',
  'molding':            'plastics',
  'restoration':        'residential-1',
  'other-room':         'other',

  // ── Process track ──
  'dry-room-process':   'battery',
  'pharma-process':     'pharmaceutical',
  'resin':              'plastics',
  'candy-process':      'processing-1',
  'investment-casting': 'manufacturing',
  'powder':             'conveying',
  'food-drying':        'food',
  'seed-process':       'silo',
  'lyo':                'pharmaceutical',
  'coatings':           'automotive',
  'other-process':      'other',
}

/** The `rooms` render key for an application preset, or undefined if unmapped. */
export const renderKeyForPreset = (presetKey: string | undefined): string | undefined =>
  presetKey ? PRESET_RENDER[presetKey] : undefined
