-- ─────────────────────────────────────────────────────────────────────────────
-- 015a_setup.sql — Step 1 of 6: categories and module rows
-- Generated by scripts/gen-learn-seed.mjs — do not edit by hand.
-- Idempotent: ON CONFLICT DO NOTHING.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Categories ──
INSERT INTO learn_categories (name, slug, description, icon, accent, display_order)
VALUES ('Onboarding', 'onboarding', 'Your first days at IAT — who we are, how we work, and the tools you''ll use.', 'Rocket', '#089447', 0)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO learn_categories (name, slug, description, icon, accent, display_order)
VALUES ('Company', 'company', 'Policies, commitments, and the bigger picture of Innovative Air Technologies.', 'Building2', '#0f766e', 1)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO learn_categories (name, slug, description, icon, accent, display_order)
VALUES ('Safety', 'safety', 'Stay safe on the floor and in the field with IAT''s safety procedures.', 'ShieldCheck', '#b45309', 2)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO learn_categories (name, slug, description, icon, accent, display_order)
VALUES ('Technical Training', 'technical-training', 'Hands-on technical know-how — engineering, wiring, testing, and shipping.', 'Wrench', '#1d4ed8', 3)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO learn_categories (name, slug, description, icon, accent, display_order)
VALUES ('Products & Tools', 'products-tools', 'Our product lines and the software tools that support them.', 'Package', '#7c3aed', 4)
ON CONFLICT (slug) DO NOTHING;

-- ── Modules ──
-- ── Welcome to IAT (imported) ──
INSERT INTO learn_modules (category_id, title, slug, description, display_order, is_published, source_file, import_status)
SELECT c.id, 'Welcome to IAT', 'welcome-to-iat', 'Introduces new employees to Innovative Air Technologies through a presidential welcome message, company history and vision, team bios, and the nine core values that guide how IAT operates.', 0, TRUE, 'Welcome to IAT.pdf', 'imported'
FROM learn_categories c WHERE c.slug = 'onboarding'
ON CONFLICT (category_id, slug) DO NOTHING;
-- ── New Rep Onboarding (imported) ──
INSERT INTO learn_modules (category_id, title, slug, description, display_order, is_published, source_file, import_status)
SELECT c.id, 'New Rep Onboarding', 'new-rep-onboarding', 'A comprehensive onboarding guide for new Innovative Air Technologies sales representatives covering company culture, product knowledge, sales strategy, order processes, and commission structure.', 1, TRUE, 'New Rep Onboarding.pdf', 'imported'
FROM learn_categories c WHERE c.slug = 'onboarding'
ON CONFLICT (category_id, slug) DO NOTHING;
-- ── How we Use Trainual at IAT (imported) ──
INSERT INTO learn_modules (category_id, title, slug, description, display_order, is_published, source_file, import_status)
SELECT c.id, 'How we Use Trainual at IAT', 'how-we-use-trainual-at-iat', 'Introduces Trainual as IAT''s central knowledge hub, explains expectations for how staff should use it, and covers the Trainual University orientation, mobile app, and support contact.', 2, TRUE, 'How we Use Trainual at IAT.pdf', 'imported'
FROM learn_categories c WHERE c.slug = 'onboarding'
ON CONFLICT (category_id, slug) DO NOTHING;
-- ── Company Commitments (imported) ──
INSERT INTO learn_modules (category_id, title, slug, description, display_order, is_published, source_file, import_status)
SELECT c.id, 'Company Commitments', 'company-commitments', 'Covers IAT''s core workplace commitments: open communication, non-harassment and non-discrimination policies, a drug- and alcohol-free environment, an open-door policy, and payroll practices.', 3, TRUE, 'Company Commitments.pdf', 'imported'
FROM learn_categories c WHERE c.slug = 'company'
ON CONFLICT (category_id, slug) DO NOTHING;
-- ── Company Policies (imported) ──
INSERT INTO learn_modules (category_id, title, slug, description, display_order, is_published, source_file, import_status)
SELECT c.id, 'Company Policies', 'company-policies', 'A comprehensive guide to Innovative Air Technologies company policies covering workplace conduct, dress code, privacy, property, gossip, weapons, attendance, leave, email, conflict resolution, discipline, and voluntary termination.', 4, TRUE, 'Company Policies.pdf', 'imported'
FROM learn_categories c WHERE c.slug = 'company'
ON CONFLICT (category_id, slug) DO NOTHING;
-- ── IAT (imported) ──
INSERT INTO learn_modules (category_id, title, slug, description, display_order, is_published, source_file, import_status)
SELECT c.id, 'IAT', 'iat', 'Covers IAT''s founding mission, core values, what makes the company different, and foundational dehumidification concepts including humidity science, desiccant technology, and how everything connects to the work employees do every day.', 5, TRUE, 'IAT.pdf', 'imported'
FROM learn_categories c WHERE c.slug = 'company'
ON CONFLICT (category_id, slug) DO NOTHING;
-- ── Safety Procedures (imported) ──
INSERT INTO learn_modules (category_id, title, slug, description, display_order, is_published, source_file, import_status)
SELECT c.id, 'Safety Procedures', 'safety-procedures', 'Covers workplace safety expectations at Innovative Air Technologies, including hazard recognition, Lean/Kaizen safety principles, PPE requirements, housekeeping standards, and safe handling procedures for equipment and confined spaces.', 6, TRUE, 'Safety Procedures.pdf', 'imported'
FROM learn_categories c WHERE c.slug = 'safety'
ON CONFLICT (category_id, slug) DO NOTHING;
-- ── Dessicant Dehumidification Training (imported) ──
INSERT INTO learn_modules (category_id, title, slug, description, display_order, is_published, source_file, import_status)
SELECT c.id, 'Dessicant Dehumidification Training', 'dessicant-dehumidification-training', 'A comprehensive technical course covering how solid desiccant dehumidifiers work, their components, the airflow process, how they compare to refrigerant-based systems, factors affecting dehumidification loads, and common industrial applications.', 7, TRUE, 'Dessicant Dehumidification Training.pdf', 'imported'
FROM learn_categories c WHERE c.slug = 'technical-training'
ON CONFLICT (category_id, slug) DO NOTHING;
-- ── Electrical Wiring Training (imported) ──
INSERT INTO learn_modules (category_id, title, slug, description, display_order, is_published, source_file, import_status)
SELECT c.id, 'Electrical Wiring Training', 'electrical-wiring-training', 'Step-by-step engineering process procedures covering electrical drawing and BOM release, blower and coil selection, desiccant wheel sizing, submittal creation workflows, and as-built drawing filing for IAT dehumidification units.', 8, TRUE, 'Electrical Wiring Training.pdf', 'imported'
FROM learn_categories c WHERE c.slug = 'technical-training'
ON CONFLICT (category_id, slug) DO NOTHING;
-- ── Engineering (imported) ──
INSERT INTO learn_modules (category_id, title, slug, description, display_order, is_published, source_file, import_status)
SELECT c.id, 'Engineering', 'engineering', 'Comprehensive engineering training covering IAT dehumidification systems, design procedures, controls, electrical systems, and production workflows for all engineering disciplines.', 9, TRUE, 'Engineering.pdf', 'imported'
FROM learn_categories c WHERE c.slug = 'technical-training'
ON CONFLICT (category_id, slug) DO NOTHING;
-- ── Testing Training (imported) ──
INSERT INTO learn_modules (category_id, title, slug, description, display_order, is_published, source_file, import_status)
SELECT c.id, 'Testing Training', 'testing-training', 'Step-by-step procedures for testing Compact Units and Rotor/IDP Units, covering electrical power verification, motor rotation checks, airflow and pressure switch testing, decibel measurement, and final system validation.', 10, TRUE, 'Testing Training.pdf', 'imported'
FROM learn_categories c WHERE c.slug = 'technical-training'
ON CONFLICT (category_id, slug) DO NOTHING;
-- ── Shipping Training (imported) ──
INSERT INTO learn_modules (category_id, title, slug, description, display_order, is_published, source_file, import_status)
SELECT c.id, 'Shipping Training', 'shipping-training', 'Step-by-step procedures for cleaning, labeling, packaging, and shipping Compact dehumidifier units, including photo documentation requirements.', 11, TRUE, 'Shipping Training.pdf', 'imported'
FROM learn_categories c WHERE c.slug = 'technical-training'
ON CONFLICT (category_id, slug) DO NOTHING;
-- ── Our Products (imported) ──
INSERT INTO learn_modules (category_id, title, slug, description, display_order, is_published, source_file, import_status)
SELECT c.id, 'Our Products', 'our-products', 'An overview of IAT''s three product lines — Compact, Rotor, and IDP — covering their key features, capabilities, and applications.', 12, TRUE, 'Our Products.pdf', 'imported'
FROM learn_categories c WHERE c.slug = 'products-tools'
ON CONFLICT (category_id, slug) DO NOTHING;
-- ── Using DryWare (imported) ──
INSERT INTO learn_modules (category_id, title, slug, description, display_order, is_published, source_file, import_status)
SELECT c.id, 'Using DryWare', 'using-dryware', 'Step-by-step guide to using the DryWare psychrometric calculator app, covering the desiccant wheel calculator, temperature and humidity inputs, air mixing, airflow CFM sizing, weather data lookup, and ship date estimation.', 13, TRUE, 'Using DryWare.pdf', 'imported'
FROM learn_categories c WHERE c.slug = 'products-tools'
ON CONFLICT (category_id, slug) DO NOTHING;