-- ─────────────────────────────────────────────────────────────────────────────
-- 015d_safety.sql — Step 4 of 6: Safety lessons
-- Generated by scripts/gen-learn-seed.mjs — do not edit by hand.
-- Idempotent: ON CONFLICT DO NOTHING.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Lessons: Safety Procedures ──
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Why We Need Safety Procedures', 'why-we-need-safety-procedures', '<h2>Why We Need Safety Procedures</h2><figure class="img-missing"><figcaption>📷 Image from Trainual: Embedded video — "Importance of Safety Guidelines for Everyone" (1 min 3 sec) — re-upload via admin editor</figcaption></figure><p>Welcome to the Safety Training Course at Innovative Air Technologies.</p><figure class="img-missing"><figcaption>📷 Image from Trainual: Photo of IAT team member in colorful jacket — re-upload via admin editor</figcaption></figure><p>At Innovative Air Technologies, safety is more than a priority — it&apos;s a core part of who we are. Whether you&apos;re assembling our industrial desiccant dehumidifiers, maintaining equipment in the field, or working in the office, ensuring a safe work environment is essential to our success and the well-being of all team members.</p><p>This course will provide you with the knowledge and tools to identify risks, follow best practices, and cultivate a culture of safety. Together, we can protect ourselves, our teammates, and the customers who rely on our products. Remember, safety is everyone&apos;s responsibility, and by working together, we can achieve a workplace where safety is second nature.</p><p>Let&apos;s get started!</p>', 0, TRUE, 3
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Our Commitment to You', 'our-commitment-to-you', '<h2>Our Commitment to You</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 1, TRUE, 2
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Recognizing Dangers in the Workplace', 'recognizing-dangers-in-the-workplace', '<h2>Recognizing Dangers in the Workplace</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 2, TRUE, 3
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Lean is SAFE!', 'lean-is-safe', '<h2>Lean is SAFE!</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 3, TRUE, 3
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'What is Kaizen?', 'what-is-kaizen', '<h2>What is Kaizen?</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 4, TRUE, 3
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Correcting Unsafe Actions', 'correcting-unsafe-actions', '<h2>Correcting Unsafe Actions</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 5, TRUE, 3
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Reporting', 'reporting', '<h2>Reporting</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 6, TRUE, 2
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Why Gloves Matter', 'why-gloves-matter', '<h2>Why Gloves Matter</h2><p>Safety gloves play a crucial role in protecting workers from various hazards present in manufacturing environments. At Innovative Air Technologies, we prioritize the safety and well-being of our employees by ensuring that they wear appropriate safety gloves while working. These gloves act as a barrier against sharp objects, chemicals, and other potential risks that could cause harm to the hands.</p><p>Safety gloves enable team members to handle tools and equipment with confidence, reducing the likelihood of accidents or injuries. This, in turn, contributes to a smoother workflow and better overall performance in our manufacturing facilities.</p>', 7, TRUE, 3
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Safety Video — Gloves', 'safety-video-gloves', '<h2>Safety Video — Gloves</h2><figure class="img-missing"><figcaption>📷 Image from Trainual: Embedded YouTube video — "IAT Safety 101: Safety Gloves" (Innovative Air Technologies / WORKPLACE SAFETY: SAFETY GLOVES) — re-upload via admin editor</figcaption></figure>', 8, TRUE, 3
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Protective Eyewear', 'protective-eyewear', '<h2>Protective Eyewear</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 9, TRUE, 2
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Slips, Trips, and Falls', 'slips-trips-and-falls', '<h2>Slips, Trips, and Falls</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 10, TRUE, 3
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Fire Extinguishers', 'fire-extinguishers', '<h2>Fire Extinguishers</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 11, TRUE, 2
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Hearing Protection', 'hearing-protection', '<h2>Hearing Protection</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 12, TRUE, 2
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Clean is King', 'clean-is-king', '<h2>Clean is King</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 13, TRUE, 2
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'No Horseplay', 'no-horseplay', '<h2>No Horseplay</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 14, TRUE, 1
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Avoiding Verbal Injury', 'avoiding-verbal-injury', '<h2>Avoiding Verbal Injury</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 15, TRUE, 2
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Sharp Objects', 'sharp-objects', '<h2>Sharp Objects</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 16, TRUE, 2
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Clear the Walkway', 'clear-the-walkway', '<h2>Clear the Walkway</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 17, TRUE, 2
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Safety Support', 'safety-support', '<h2>Safety Support</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 18, TRUE, 2
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Considering Others', 'considering-others', '<h2>Considering Others</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 19, TRUE, 2
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'VFD Electrical Connections', 'vfd-electrical-connections', '<h2>VFD Electrical Connections</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 20, TRUE, 3
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Loading a Unit Safely', 'loading-a-unit-safely', '<h2>Loading a Unit Safely</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 21, TRUE, 3
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
INSERT INTO learn_lessons (module_id, title, slug, content, display_order, is_published, estimated_minutes)
SELECT m.id, 'Working in Confined Spaces', 'working-in-confined-spaces', '<h2>Working in Confined Spaces</h2><p><em>Content for this lesson is maintained in Trainual. Please re-enter the body text via the admin editor.</em></p>', 22, TRUE, 3
FROM learn_modules m JOIN learn_categories c ON c.id = m.category_id
WHERE c.slug = 'safety' AND m.slug = 'safety-procedures'
ON CONFLICT (module_id, slug) DO NOTHING;
